"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-05 01:55:45.775410
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('body_part', sa.String(length=50), nullable=False),
    sa.Column('primary_muscle', sa.String(length=100), nullable=False),
    sa.Column('secondary_muscle', sa.String(length=100), nullable=False),
    sa.Column('equipment', sa.String(length=50), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('video_url', sa.String(length=512), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=512), nullable=True),
    sa.Column('steps', sa.Text(), nullable=False),
    sa.Column('cautions', sa.Text(), nullable=False),
    sa.Column('met', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('aliases', sa.String(length=255), nullable=False),
    sa.Column('calories_kcal', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carb_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('tags', sa.String(length=255), nullable=False),
    sa.Column('cover_url', sa.String(length=512), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_goals',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('resistance_principle', sa.Text(), nullable=False),
    sa.Column('cardio_principle', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('openid', sa.String(length=128), nullable=True),
    sa.Column('nickname', sa.String(length=64), nullable=False),
    sa.Column('avatar', sa.String(length=512), nullable=True),
    sa.Column('session_nonce', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('openid')
    )
    op.create_table('cardio_prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_code', sa.String(length=32), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('modes', sa.String(length=255), nullable=False),
    sa.Column('sessions_min', sa.Integer(), nullable=False),
    sa.Column('sessions_max', sa.Integer(), nullable=False),
    sa.Column('minutes_min', sa.Integer(), nullable=False),
    sa.Column('minutes_max', sa.Integer(), nullable=False),
    sa.Column('intensity_method', sa.String(length=16), nullable=False),
    sa.Column('intensity_min', sa.Float(), nullable=False),
    sa.Column('intensity_max', sa.Float(), nullable=False),
    sa.Column('interval_work_seconds', sa.Integer(), nullable=True),
    sa.Column('interval_rest_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['goal_code'], ['training_goals.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('goal_code', 'level', name='uq_goal_cardio_level')
    )
    op.create_index(op.f('ix_cardio_prescriptions_goal_code'), 'cardio_prescriptions', ['goal_code'], unique=False)
    op.create_table('favorite_exercises',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'exercise_id')
    )
    op.create_table('favorite_recipes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'recipe_id')
    )
    op.create_table('goal_exercise_prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_code', sa.String(length=32), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('movement_pattern', sa.String(length=32), nullable=False),
    sa.Column('sets_min', sa.Integer(), nullable=False),
    sa.Column('sets_max', sa.Integer(), nullable=False),
    sa.Column('reps_min', sa.Integer(), nullable=True),
    sa.Column('reps_max', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=False),
    sa.Column('rir_min', sa.Integer(), nullable=True),
    sa.Column('rir_max', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['goal_code'], ['training_goals.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('goal_code', 'exercise_id', name='uq_goal_exercise')
    )
    op.create_index(op.f('ix_goal_exercise_prescriptions_exercise_id'), 'goal_exercise_prescriptions', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_goal_exercise_prescriptions_goal_code'), 'goal_exercise_prescriptions', ['goal_code'], unique=False)
    op.create_table('meal_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(length=16), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('calories_kcal', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carb_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_records_record_date'), 'meal_records', ['record_date'], unique=False)
    op.create_index(op.f('ix_meal_records_user_id'), 'meal_records', ['user_id'], unique=False)
    op.create_table('recipe_ingredients',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('amount_g', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('recipe_id', 'ingredient_id')
    )
    op.create_table('recipe_steps',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('recipe_id', 'order_no')
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('current_weight_kg', sa.Float(), nullable=True),
    sa.Column('target_weight_kg', sa.Float(), nullable=True),
    sa.Column('goal_type', sa.String(length=16), nullable=False),
    sa.Column('daily_calorie_target', sa.Float(), nullable=False),
    sa.Column('protein_target_g', sa.Float(), nullable=False),
    sa.Column('carb_target_g', sa.Float(), nullable=False),
    sa.Column('fat_target_g', sa.Float(), nullable=False),
    sa.Column('profile_completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('weight_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'record_date', name='uq_weight_user_date')
    )
    op.create_index(op.f('ix_weight_records_record_date'), 'weight_records', ['record_date'], unique=False)
    op.create_index(op.f('ix_weight_records_user_id'), 'weight_records', ['user_id'], unique=False)
    op.create_table('workout_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workout_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('calories_kcal', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_sessions_user_id'), 'workout_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_workout_sessions_workout_date'), 'workout_sessions', ['workout_date'], unique=False)
    op.create_table('workout_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('set_no', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_sets_session_id'), 'workout_sets', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_sets_session_id'), table_name='workout_sets')
    op.drop_table('workout_sets')
    op.drop_index(op.f('ix_workout_sessions_workout_date'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_user_id'), table_name='workout_sessions')
    op.drop_table('workout_sessions')
    op.drop_index(op.f('ix_weight_records_user_id'), table_name='weight_records')
    op.drop_index(op.f('ix_weight_records_record_date'), table_name='weight_records')
    op.drop_table('weight_records')
    op.drop_table('user_profiles')
    op.drop_table('recipe_steps')
    op.drop_table('recipe_ingredients')
    op.drop_index(op.f('ix_meal_records_user_id'), table_name='meal_records')
    op.drop_index(op.f('ix_meal_records_record_date'), table_name='meal_records')
    op.drop_table('meal_records')
    op.drop_index(op.f('ix_goal_exercise_prescriptions_goal_code'), table_name='goal_exercise_prescriptions')
    op.drop_index(op.f('ix_goal_exercise_prescriptions_exercise_id'), table_name='goal_exercise_prescriptions')
    op.drop_table('goal_exercise_prescriptions')
    op.drop_table('favorite_recipes')
    op.drop_table('favorite_exercises')
    op.drop_index(op.f('ix_cardio_prescriptions_goal_code'), table_name='cardio_prescriptions')
    op.drop_table('cardio_prescriptions')
    op.drop_table('users')
    op.drop_table('training_goals')
    op.drop_table('recipes')
    op.drop_table('ingredients')
    op.drop_table('exercises')
    # ### end Alembic commands ###
